# Generated by Django 4.1.2 on 2022-10-26 21:35

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from django_finances.fields import UUID4Field
from django_finances.settings import Settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialEntity',
            fields=[
                ('id', UUID4Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID') if Settings.USE_UUID else models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=Settings.FINANCIAL_ENTITY_NAME_MAX_LENGTH, verbose_name='name')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'financial entity',
                'verbose_name_plural': 'financial entities',
            },
        ),
    ] if Settings.FINANCIAL_ENTITY_MODEL == 'django_finances.FinancialEntity' else []
