# Generated by Django 4.1.2 on 2022-10-28 18:31

from django.db import migrations, models
import django.utils.timezone

from django_finances.settings import Settings


class Migration(migrations.Migration):

    dependencies = [
        ('django_finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialentity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialentity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ] if Settings.FINANCIAL_ENTITY_MODEL == 'django_finances.FinancialEntity' else []
