# Generated by Django 4.0.4 on 2022-05-21 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from django_transactions.settings import Settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=Settings.FINANCIAL_ENTITY_NAME_MAX_LENGTH)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'financial entities',
            },
        ),
    ]
