# Generated by Django 4.1.2 on 2022-10-26 22:25

import uuid

from django.db import migrations, models
import django.db.models.deletion

from django_finances.fields import UUID4Field
from django_finances.settings import Settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MolliePayment',
            fields=[
                ('id', UUID4Field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID') if Settings.USE_UUID else models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=32, verbose_name='identifier')),
                ('checkout_url', models.CharField(max_length=128, verbose_name='checkout url')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mollie_payment', to='payments.payment', verbose_name='payment')),
            ],
            options={
                'verbose_name': 'mollie payment',
                'verbose_name_plural': 'mollie payments',
            },
        ),
    ]
