# Generated by Django 4.0.4 on 2022-06-25 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_add_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MolliePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=32)),
                ('checkout_url', models.CharField(max_length=128)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mollie_payment', to='payments.payment')),
            ],
        ),
    ]
