# Generated by Django 4.0.4 on 2022-05-21 22:18

from django.db import migrations, models
import django.db.models.deletion

from django_finances.settings import Settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField() if Settings.USE_BIG_INTEGER else models.IntegerField()),
                ('description', models.TextField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='django_finances.financialentity')),
            ] + ([
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled', to='transactions.transaction')),
            ] if Settings.TRANSACTION_SETTLEMENT_ENABLED else []),
        ),
    ]
