# Generated by Django 4.0.4 on 2022-05-21 22:25

from django.db import migrations, models
import django.db.models.deletion

from django_finances.settings import Settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ] if Settings.TRANSACTION_ENABLED else [
        ('django_finances', '0001_initial'),
    ]

    _additional_fields: list[models.Field] = [
        ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='transactions.transaction')),
    ] if Settings.TRANSACTION_ENABLED else [
        ('amount', models.IntegerField()),
        ('description', models.TextField()),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ] + _additional_fields,
        ),
    ]
